export const areaTableData: Array<FormFieldInterface> = [
  {
    id: 'name',
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    priority: 0,
  },
  {
    id: 'description',
    name: 'description',
    label: 'Description',
    type: 'text',
    required: false,
    priority: 0,
  },
  {
    id: 'building',
    name: 'building',
    label: 'Owner',
    type: 'select',
    entitySingle: 'building',
    entityPlural: 'buildings',
    selectValues: ['ragioneSociale'],
    grantTo: ['super_admin'],
    required: false,
    priority: 100,
  },
  {
    id: 'owner',
    name: 'owner',
    label: 'Owner',
    type: 'select',
    entitySingle: 'owner',
    entityPlural: 'owners',
    selectValues: ['ragioneSociale'],
    grantTo: ['super_admin'],
    required: false,
    priority: 100,
  },
];
