export const bookmarkTableData: Array<FormFieldInterface> = [
  {
    id: 'title',
    name: 'title',
    label: 'Title',
    placeholder: 'Bookmark title',
    type: 'text',
    required: true,
    priority: 1,
  },
  // {
  //   id: 'entity',
  //   name: 'entity',
  //   label: 'entity',
  //   placeholder: "Bookmarks' entity. will be static select",
  //   type: 'text',
  //   required: true,
  //   priority: 1,
  // },
  {
    id: 'threads',
    name: 'threads',
    label: 'threads',
    type: 'select',
    multi: true,
    _entity: 'threads',
    selectValues: ['title'],
    required: false,
    priority: 1,
  },
  {
    id: 'note',
    name: 'note',
    label: 'note',
    placeholder: 'note',
    type: 'long-text',
    required: true,
    priority: 1,
  },
  {
    id: 'createdAt',
    name: 'createdAt',
    label: 'Created date',
    placeholder: '',
    type: 'text',
    noForm: true,
    required: false,
    priority: 1,
  },
];
