export const commentTableData: Array<FormFieldInterface> = [
  {
    id: 'title',
    name: 'title',
    label: 'Title',
    placeholder: 'Title of the comment',
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'subtitle',
    name: 'subtitle',
    label: 'SubTitle',
    placeholder: 'Title of the comment',
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'body',
    name: 'body',
    label: 'lorem ipsum...',
    placeholder: "Comment' body",
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'password',
    name: 'password',
    label: 'Password for private use',
    placeholder: 'secret_$$',
    type: 'text',
    required: false,
    priority: 1,
  },
  {
    id: 'private',
    name: 'private',
    label: 'Hide comment.',
    type: 'boolean',
    required: false,
    priority: 1,
  },
  {
    id: 'anonymous',
    name: 'anonymous',
    label: 'Hide comment.',
    type: 'boolean',
    required: false,
    priority: 1,
  },

  {
    id: 'building',
    name: 'building',
    label: 'building',
    type: 'select',
    entitySingle: 'building',
    entityPlural: 'buildings',
    selectValues: ['name'],
    required: true,
    priority: 2,
  },
  {
    id: 'owner',
    name: 'owner',
    label: 'Owner',
    type: 'select',
    entitySingle: 'owner',
    entityPlural: 'owners',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'createdBy',
    name: 'createdBy',
    label: 'Created by',
    type: 'select',
    entitySingle: 'user',
    entityPlural: 'users',
    selectValues: ['name', 'email'],
    required: false,
    priority: 2,
  },
];
