export const fundTableData: Array<FormFieldInterface> = [
  {
    id: 'amount',
    name: 'amount',
    label: 'amount',
    placeholder: 'amount of the comment',
    type: 'number',
    required: true,
    priority: 1,
  },
  {
    id: 'fundRules',
    name: 'fundRules',
    label: 'fundRules',
    placeholder: 'fundRules',
    type: 'number',
    required: true,
    priority: 1,
  },
  {
    id: 'building',
    name: 'building',
    label: 'Building',
    type: 'select',
    entitySingle: 'building',
    entityPlural: 'buildings',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'user',
    name: 'user',
    label: 'created by',
    type: 'select',
    entitySingle: 'user',
    entityPlural: 'users',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
];
