export const instancesTableData: Array<FormFieldInterface> = [
  {
    id: 'name',
    name: 'name',
    label: 'Name',
    placeholder: 'name of the person/room',
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'description',
    name: 'description',
    label: 'description',
    placeholder: 'Description',
    type: 'text',
    required: true,
    priority: 1,
  },

  {
    id: 'building',
    name: 'building',
    label: 'Building',
    type: 'select',
    _entity: 'buildings',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'type',
    name: 'type',
    label: 'created by',
    type: 'static-select',
    multi: true,
    options: [
      { label: 'user', value: 'user' },
      { label: 'space', value: 'space' },
    ],
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'user',
    name: 'user',
    label: 'created by',
    type: 'select',
    multi: true,
    _entity: 'users',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'proposals',
    name: 'proposals',
    label: 'Proposals',
    placeholder: 'Select proposals',
    type: 'select',
    multi: true,
    _entity: 'proposals',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
];
