export const maintenancesTableData: Array<FormFieldInterface> = [
  {
    id: 'title',
    name: 'title',
    label: 'Maintenance',
    placeholder: 'Tubo rotto, Perdita acqua, etc...',
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'description',
    name: 'description',
    label: 'Descriptions',
    placeholder: '3F - dopo la scala a destra...',
    type: 'long-text',
    required: true,
    priority: 1,
  },
  {
    id: 'images',
    name: 'images',
    label: 'Photos',
    type: 'image',

    multi: true,
    accept: 'image/*',
    // type: 'dropzone',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'attachments',
    name: 'attachments',
    multi: true,
    accept: '',
    label: 'Attachments',
    type: 'attachment',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'maintainters',
    name: 'maintainters',
    multi: true,
    label: 'contatti dei possibili manutentori',
    placeholder: 'manutentore.sevesco@idraulico.it, aggiusto.io@idraulico.it',
    type: 'text',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  // {
  //   id: 'building',
  //   name: 'building',
  //   label: 'created by',
  //   type: 'select',
  //   multi: true,
  //   _entity: 'buildings',
  //   selectValues: ['name'],
  //   required: false,
  //   priority: 2,
  // },
  {
    id: 'severity',
    name: 'severity',
    label: 'Importanza',
    type: 'text',
    required: false,
    priority: 2,
  },
];
