export const maintenancesTableData: Array<FormFieldInterface> = [
  {
    id: 'name',
    name: 'name',
    label: 'Nome',
    type: 'text',
    required: true,
    priority: 0,
  },
  {
    id: 'homepage',
    name: 'homepage',
    label: 'Homepage',
    type: 'text',
    required: false,
    priority: 0,
  },
  {
    id: 'type',
    name: 'type',
    label: 'Tipo',
    type: 'text',
    required: false,
    priority: 0,
  },
  {
    id: 'tel',
    name: 'tel',
    label: 'Telefono',
    type: 'text',
    required: false,
    priority: 0,
  },
  {
    id: 'email',
    name: 'email',
    label: 'Email',
    type: 'text',
    required: true,
    priority: 0,
  },
  {
    id: 'logo',
    name: 'logo',
    label: 'Logo',
    type: 'text',
    required: false,
    priority: 0,
  },
  {
    id: 'description',
    name: 'description',
    label: 'Descrizione',
    type: 'text',
    required: false,
    priority: 0,
  },
  {
    id: 'address',
    name: 'address',
    label: 'Indirizzo',
    type: 'text',
    required: false,
    priority: 0,
  },
  {
    id: 'isIndividual',
    name: 'isIndividual',
    label: 'Individuale',
    type: 'boolean',
    required: false,
    priority: 0,
  },
];
