export const proposalTableData: Array<FormFieldInterface> = [
  {
    id: 'amount',
    name: 'amount',
    label: 'Amount money',
    placeholder: '1000$',
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'description',
    name: 'description',
    label: 'description',
    placeholder: 'Description',
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'fundRule',
    name: 'fundRule',
    label: 'fundRule',
    type: 'select',
    _entity: 'fundRules',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'building',
    name: 'building',
    label: 'created by',
    type: 'select',
    multi: true,
    _entity: 'buildings',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
  {
    id: 'user',
    name: 'user',
    label: 'created by',
    type: 'select',
    multi: true,
    _entity: 'users',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
];
