export const userSettingTableData: Array<FormFieldInterface> = [
  {
    id: 'pushNotification',
    name: 'pushNotification',
    label: 'pushNotification',
    placeholder: '',
    type: 'boolean',
    required: true,
    priority: 1,
  },
  {
    id: 'smsNotification',
    name: 'smsNotification',
    label: 'smsNotification',
    placeholder: '',
    type: 'boolean',
    required: true,
    priority: 1,
  },
  {
    id: 'user',
    name: 'user',
    label: 'created by',
    type: 'select',
    multi: true,
    entitySingle: 'user',
    entityPlural: 'users',
    selectValues: ['name'],
    required: false,
    priority: 2,
  },
];
