export const usersTableData: Array<FormFieldInterface> = [
  {
    id: 'name',
    name: 'name',
    label: 'Nome',
    placeholder: 'First name',
    type: 'text',
    required: true,
    priority: 1,
  },
  {
    id: 'surname',
    name: 'surname',
    label: 'Cognome',
    type: 'text',
    required: false,
    priority: 2,
  },
  {
    id: 'role',
    name: 'role',
    label: 'Ruolo',
    type: 'text',
    // options: ['super_admin', 'admin', 'operatore', 'supervisore', 'manutentore'],
    options: [{ value: 'static-slect-value', label: 'static-label' }],

    required: true,
    priority: 3,
  },
  {
    id: 'email',
    name: 'email',
    label: 'Email',
    type: 'text',
    required: true,
    priority: 4,
  },
  {
    id: 'phone',
    name: 'phone',
    label: 'Telefono',
    type: 'text',
    required: false,
    priority: 5,
  },
  {
    id: 'password',
    name: 'password',
    label: 'Password',
    type: 'text',
    required: true,
    noTable: true,
    priority: 6,
  },
  {
    id: 'buildings',
    name: 'buildings',
    label: 'Struttura',
    type: 'select',
    entitySingle: 'building',
    entityPlural: 'buildings',
    selectValues: ['name'],
    multi: true,
    required: false,
    priority: 100,
  },
  {
    id: 'owner',
    name: 'owner',
    label: 'Owner',
    type: 'select',
    entitySingle: 'owner',
    entityPlural: 'owners',
    selectValues: ['name'],
    grantTo: ['super_admin'],
    required: false,
    priority: 100,
  },
];
